### ISSUE TITLE
ChaCha20?

### ISSUE THREAD

**Issue by hhartzer** [dchest/geli-threefish#1]
This sounds really cool! Curious, is threefish still relevant when ChaCha20 is somewhat prevalent?

Thanks!

**Comment by dchest** [comment]
It was never relevant :) However, ChaCha20 can't be used here, since it's a stream cipher, while Threefish is a block cipher. If a disk block is encrypted by ChaCha20, and you write new data in this block, you get reused key/nonce — see https://en.wikipedia.org/wiki/Stream_cipher_attacks#Reused_key_attack — and thus can recover data without decrypting it if you have the contents of encrypted disk from two different points in time.

**Comment by hhartzer** [comment]
Ah, cool! Thanks for explaining.

It sounds like there's just AES and Camellia options for geli these days.
